matrix:
  include:    
    - os: linux
    - os: osx
      osx_image: xcode8.3

dist: trusty
sudo: true
language:
  - cpp
compiler:
  - clang

before_install:
  - eval "${MATRIX_EVAL}"
  - git submodule update --init --recursive;
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      sudo add-apt-repository ppa:beineri/opt-qt571-trusty -y;
      sudo apt-get update -qq;
      sudo apt-get install -qq cmake build-essential;
    fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      brew update;
      brew upgrade cmake;
    fi

script:
  - gcc -v && g++ -v && cmake --version
  - cmake ./;
  - make;

notifications:
  email: true
