matrix:
  include:    
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
      env:
        - MATRIX_EVAL="CC=clang-3.6 && CXX=clang++-3.6"
    - os: osx
      osx_image: xcode8.3

dist: trusty
sudo: true
language:
  - cpp
compiler:
  - clang

before_install:
  - eval "${MATRIX_EVAL}"
  - git submodule update --init --recursive;
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      sudo add-apt-repository ppa:beineri/opt-qt571-trusty -y;
      sudo apt-get update -qq;
      sudo apt-get install -qq cmake libxml2-dev libmotif-dev build-essential;    
    fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      brew update;
      brew install openmotif;
      brew upgrade libxml2;
      brew upgrade cmake;
    fi

script:
  - gcc -v && g++ -v && cmake --version
  - cmake ./;
  - make;

notifications:
  email: true
