os:
  - linux
  - osx

sudo: true

language: cpp
compiler: gcc

dist: trusty

before_install:
  - git submodule update --init --recursive
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      sudo add-apt-repository ppa:beineri/opt-qt571-trusty ppa:ubuntu-toolchain-r/test -y;
    fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      sudo apt-get update -qq;
    fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      brew update;
    fi

install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      sudo apt-get install -qq qt57base cmake libxml2-dev libmotif-dev; source /opt/qt57/bin/qt57-env.sh;
    fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
     brew install cmake;
     brew install openmotif;
     brew install libxml2;
     brew install qt5;
     brew link --force qt5;
    fi

script:
  - cmake
  - make

notifications:
  email: true